import dash
from dash import html

dash.register_page(__name__, path='/about')

layout = html.Div(className="about-container", children=[ 
    #TODO write the about section
    html.H2("About"),
    html.P("INTRO"),
    html.P("The Stormlight Archive is a five-book epic fantasy series by Brandon Sanderson. This webpage is a class project created by Matt Caputo, Heming Chen, and Violet Hall. We have taken the text of the first two books, The Way of Kings and Words of Radiance, and performed various analytical techniques on the texts to create interesting and easily interpretable visualizations. We hope you enjoy messing around with what we've found!"),
    html.P("Working Together"),
    html.P("This project was a highly collaborative effort from Matt Caputo, Heming Chen, and Violet Hall. The collaboration started in the planning phase where each member was tasked with coming up with the visualizations they thought would give an interesting analysis of the story. Then throughout the workflow all members played parts in each role. During the data finding and cleaning phase Matt was able to make full text documents for each work, cleaning out any unnecessary text. Then all members set to working together to manually break down the text into chapters and some sub chapters by POV character, Title, whether it was a backstory, and the text of the chapter. Matt then took the lead on the data generation, breaking the CSV into more specific elements related to each graphs needs. Claude was used to help fit existing code from the Digital Texts course series to this particular use. The next step was the platform. Heming set up the base of the website and designed many of the interactive and structural features for the site. The visualization was a group effort from conception to end with all members helping to write and rewrite the visualization tools. The interpretation of the CSVs into the figures was AI-assisted. Matt mainly focused on background structure, as he had the knowledge of the analysis tools being presented. Heming took to making these visualizations come alive with interactive features. Violet focused on stylistic elements, ensuring a consistent color palette to push the comprehension of analysis, and make it pretty and accessible. Most of the work for this project was done while sitting in the same room, with each member getting to hold council at their home. So much of what each member created was intricately inspired by and tied to the group as a whole, with constant consultation leading the way to success. "),
    html.H2("Characters (Images From Left to Right)"),
     html.H3("Kaladin Stormblessed"),
     html.P("Kaladin is the son of a surgeon hardened by the deaths of so many he has tried to protect. He is a great warrior who became a hero, learning to put others before himself and life before death."),
     html.P("Kaladin becomes enchanced with great power from a mystical Spren named Syl, who helps him fly high and destroy those who wish to harm those he loves."),
     html.H3("Shallan Davar"),
     html.P("Shallan is the artist daughter of a nobleman . She is haunted by the deaths of her parents and her part in them. She travels to work with the King's sister and along the way discovers her true power."),
     html.P("Aided by her Spren, Pattern, Shallan is able to take any disguise and use her art to create false reality."),
     html.H3("Dalinar Kholin"),
     html.P("Dalinar is the brother of the last king, uncle of the present, and a great warrior. He wants to do good by his nation and unite them into one. His dreams are pushed by nightmares that seem to be prophecy."),
     html.P("Dalinar longs to take the throne, but before he can he must take the mantle to recreate the ancient order of knights. He is empowered by the Spren of the great storm for this role."),
      html.H3("Adolin Kholin"),
     html.P("Adolin is the son of Dalinar and a great duelist. He has sorry luck with women running them all off, but he has a good heart underneath his spoiled frame."),
     html.P("Eventually he finds romance seeming to go right with Shallan. But when the ancient knights are rising and he is not among them where will his place be?"),
      html.H3("Eshonai"),
     html.P("Eshonai is the war leader of the Parshendi, a race of sentient creatures locked in bitter war with humans, after assassinating the Alethi king."),
     html.P("Eshonai turns the tides of the war with an ancient power that may offer hope for her people, but could also be their damnation."),
      html.H3("Szeth"),
     html.P("Szeth is the assassin in white hired to kill the king by the Parshendi. He was exiled from his far off home and forced to kill for whoever holds his oathstone."),
     html.P("He is tragic and cannot find peace until Kaladin defeats him in battle and takes his mighty fearful weapon."),
     html.P("DATA SOURCE"),
     html.P("The Stormlight Archive is a bestselling epic fantasy series by Brandon Sanderson. For this project, we analyzed the text of the first two Stormlight novels, The Way of Kings and Words of Radiance. These texts are under copyright. To obtain the texts, we purchased digital copies from ebooks.com. This analysis of copyrighted material constitutes fair usage, and we have been careful to not expose the copyrighted text itself to the public."),
     html.P("METHODOLOGY"),
     html.P("TEXT PARSING"),
     html.P("The foundational step for each of these analyses was to break the text into several CSV files. Once the digital watermarking was cleared from the text files using regex, we created CSVs breaking the books into chapters, paragraphs, and sentences."),
     html.P("STYLOMETRIC ANALYSIS WITH PRINCIPAL COMPONENT ANALYSIS (PCA)"),
     html.P("To create the stylometric analysis, we used the chapter-level CSV file. PCA analysis takes the n most common terms (we chose 1,000) and turns each of those terms into an axis in n-dimensional space. Each usage of each term pushes a given chapter along that term’s axis. Once each chapter has been placed, the network is projected down to 2-dimensional space. PC1 is the axis along which documents differ the most, PC2 is the next-most-different axis orthogonal to PC1. This creates a scatterplot where the stylometric distinctions between chapters are clearly displayed."),
     html.P("KEY DECISIONS"),
     html.P("Character names were stripped from the vocabulary list. The close third person prose of these novels means that every Kaladin PoV Chapter contains many, many iterations of the word “Kaladin.” Stripping these names prevents this from influencing the PCA placement."),
     html.P("Each book's mean feature vector was subtracted from its own chapters. This reduces noise and prevents the stylistic differences between books from overshadowing the stylistic differences between characters."),
     html.P("REASONING"),
     html.P("The varying Points of View between chapters is one of the most distinctive features in Sanderson's work. His fans will often praise the distinct and recognizable voices of his characters. This method of analysis lets us objectively measure the stylometric distinction between his characters, answering once and for all the question of how distinct Sanderson's prose is between PoV characters."),
     html.P("INTERPRETATION"),
     html.P("We can clearly see that each PoV character occupies a distinct space in the PCA analysis. Of the main four characters, Kaladin, Adolin, and Dalinar are somewhat overlapping, and Shallan is more distinct. This makes a lot of sense considering the soldier/scholar divide between these characters. Interestingly, the Shallan and Kaladin backstory chapters are distinct from the other chapters, and distinct in the same direction. This implies that Sanderson is not just writing the characters, but that he is giving the child versions of these characters meaningfully different perspectives from their adult selves."),
     html.P("CHARACTER CO-OCCURRENCE GRAPH"),
     html.P("This graph measures the co-occurrence of characters by chapter. We started with a list of the books’ characters. These are our nodes. Each time that two items from the list co-exist in a chapter, an edge is created between them, marked by chapter so that the user can select any section of the texts."),
     html.P("KEY DECISIONS"),
     html.P("The singular key decision for this plot was to go with co-occurrence rather than dialogue interactions. Trying to accurately pull the dialogue interactions from the text proved too difficult for the scale of this project, and would have required a lot of manual data entry."),
     html.P("REASONING"),
     html.P("Large rosters of characters are one of the defining traits of epic fantasy series. By creating this graph, and by including algorithmically derived communities, we created a handy visualization that allows a reader to keep track of which characters are interacting with each other. This is also a useful tool for tracking who the most interacted-with characters are, and we get a clear sense of which characters, even side characters, are most central to the communities represented by the Stormlight cast."),
     html.P("INTERPRETATION"),
     html.P("The community sorting algorithm was extremely effective. It correctly identified the bridge four crew, the Kholin family and the royal court, and the Shallan/Jasnah scholar group as distinct categories. It also bunched the various backstory characters together. It is extremely interesting to see the actual network of bridge four laid out this way."),
     html.P("SENTIMENT ANALYSIS"),
     html.P("To perform the Sentiment analysis, we used VADER (Valence Aware Dictionary and sEntiment Reasoner) to calculate a sentiment score paragraph-by-paragraph, and then averaged the paragraph scores to calculate a sentiment between 1 and -1 for each chapter. These are then laid out chronologically. We decided to separate and stack the two books to allow the user to compare the two books to each other."),
     html.P("KEY DECISIONS"),
     html.P("We stripped the epigraphs from the chapters, because they were often strong outliers and not necessarily representative of the chapters’ contents."),
     html.P("We also stripped dialogue tags and some other common neutral words from the text, to avoid drowning out the words with higher sentiment scores."),
     html.P("REASONING"),
     html.P("This is something of a proof-of-concept. While these results aren't particularly surprising on their own, the fact that there were recognizable dips and bumps for someone familiar with the text means that this method was indeed effective at following the positive/negative trajectory of the text. This method could be extrapolated to a much larger corpus, and show us something like 'the sentiment arc of 2010s epic fantasy.'"),
     html.P("INTERPRETATION"),
     html.P("Nothing particularly surprising about these results. Szeth is sad, Shallan is optimistic, Kaladin is depressed and then triumphant, Dalinar doubts himself then reaches a moment of clarity. As said above, this is interesting in concept as it means this method can be used more widely, but this individual result doesn't lead to any particular revelations."),
     html.P("TOPICS OVER TIME"),
     html.P("To create this graph we used BERTopic, which takes the text and finds word patterns and co-occurances that would be invisible to the human eye. BERTopic is a transformer, and captures the semantic usage of the words, rather than a simple bag-of-words approach. These patterns resulted in a list of topics, which were algorithmically culled to reduce noise, and then hand-selected to create a list of meaningful topics, which were then manually labeled."),
     html.P("KEY DECISIONS"),
     html.P("We cut character and place names from the text, to prevent names dominating topics."),
     html.P("REASONING"),
     html.P("While the stylometric analysis showed us how the characters differed from each other, the topic analysis shows us how the main concerns of the book present themselves. This clearly lets us see where backstory chapters are, where bridge four lives in the text, where shallan is talking to herself."),
     html.P("INTERPRETATION"),
     html.P("The shifting priorities of the text come into focus when looking at this graph. You can see clearly WoK's focus on the bridge crews, and the way that WoR is more engaged with the politics of the warcamps."),
     html.P("WHERE TO NEXT?"),
     html.P("The obvious next step would be to expand this analysis into the full five-book series. Beyond that the true answer depends on scope. It is my (Matt Caputo's) ambition to accumulate a corpus robust enough to be meaningfully representative of post-Tolkien fiction. Given that these texts are mostly copyrighted this is a complicated and potentially expensive task, but if I had all the resources in the world that's the direction I would go. The particular analytical techniques would need to be adjusted to account for such a large corpus, but there's a lot of publishable work in that idea."),
])
